# Generated by Django 4.2.2 on 2023-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='live_strem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
