# Generated by Django 4.2.2 on 2023-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='file',
            field=models.FileField(upload_to='gamesFile/games'),
        ),
        migrations.AlterField(
            model_name='games',
            name='sample_video',
            field=models.FileField(upload_to='gamesFile/sample_video'),
        ),
        migrations.AlterField(
            model_name='games',
            name='thumbnails',
            field=models.ImageField(upload_to='gamesFile/images'),
        ),
    ]
